### ISSUE TITLE
Implement Linear Regression (logistic)

### ISSUE THREAD

**Issue by jacluff1** [jacluff1/Star-Dased#44]
implement linear logistic regression of the exact form Dr. H asks for.

**Comment by domdobis** [comment]
I implemented Linear Regression and pushed

**Comment by jacluff1** [comment]
when you select 8 features, does it automatically include the interactions as well?

I see that you are a few commits behind master, make sure and get even with master so I can pull your changes. Thank you!

**Comment by domdobis** [comment]
8 Features does include the interaction terms as well you can use a function get_feature_names() to get the coefficents of the polynomial features
